[tools]
typst = "0.15"
typstyle = "0.15"

[settings]
idiomatic_version_file_enable_tools = ["rust"]

[env]
TYPST_ROOT = "{{config_root}}"
TYPST_FONT_PATHS = "{{config_root}}/thesis/fonts"

[vars]
THESIS_TITLE = "A population-based multi-agent approach for simulating large-scale system dynamics in discrete environments"

[tasks."fmt:typst"]
description = "Format the typst code"
run = ["typstyle -i ./ --timing"]

[tasks."export-thesis"]
description = "Export the document to PDF"
env = { THESIS_TITLE = "{{ vars.THESIS_TITLE }}" }
run = [
    'typst compile thesis/main.typ --format pdf --input "title=$THESIS_TITLE" --pdf-standard a-3u "Tim Peko BSc Bioinformatics Thesis - {{ env.THESIS_TITLE }}.pdf"'
]
