[package]
name = "pbma-cli"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
pbma-core.workspace = true
pbma-grid.workspace = true
pbma-model.workspace = true
pbma-sim.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "tick"
harness = false

[lints]
workspace = true
